# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.
#
# This Blueprint uses free instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: yunyun
      - key: N8N_BASIC_AUTH_PASSWORD
        value: shanmoumou7!
      - key: N8N_ENCRYPTION_KEY
        value: 3378hsdedwqd9ffqwfws
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

databases:
  - name: n8n-db
    plan: free
    # The free instance type is limited to 1 GB of disk
    # space.
    #
    # If you later upgrade to a paid instance type, you can
    # increase the disk size to any multiple of 5 GB by
    # setting the `diskSizeGB` property.
    #
    # diskSizeGB: 5
# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.
#
# This Blueprint uses free instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    # 修正 envVars 的縮排，它應該與 name, image, plan 等對齊
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: 123
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 123
      - key: N8N_ENCRYPTION_KEY
        value: 3378hsdedwqd9ffqwfws
      # 已刪除 N8N_PORT，n8n 會自動使用 Render 提供的 PORT
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

databases:
  - name: n8n-db
    plan: free
    # The free instance type is limited to 1 GB of disk
    # space.
    #
    # If you later upgrade to a paid instance type, you can
    # increase the disk size to any multiple of 5 GB by
    # setting the `diskSizeGB` property.
    #
    # diskSizeGB: 5
